In [ ]:
import sqlite3
import pandas as pd    
from pathlib import Path

In [7]:
caminho_db = Path("./db/projeto_vendas.db")

conexao = sqlite3.connect(caminho_db)

query_vendas = """
SELECT DISTINCT * FROM vendas
"""

query_clientes = """
SELECT * FROM clientes
"""

query_produtos = """
SELECT * FROM produtos
"""

vendas = pd.read_sql_query(query_vendas, conexao)
clientes = pd.read_sql_query(query_clientes, conexao)
produtos = pd.read_sql_query(query_produtos, conexao)

conexao.close()

display(vendas)
display(clientes)
display(produtos)

,venda_id,data_venda,cliente_id,produto_id,quantidade,preco_unitario,desconto_pct,forma_pagamento
0,V0001,2025-05-21,C001,P002,4.0,420.0,0.00,Cartão
1,V0002,2025-02-14,C009,P002,7.0,420.0,0.00,Pix
2,V0003,2025-04-30,C004,P002,1.0,420.0,0.15,Cartão
3,V0004,2025-08-18,C004,P007,5.0,150.0,0.00,Cartão
4,V0005,2025-05-23,C006,P007,3.0,150.0,0.00,Boleto
...,...,...,...,...,...,...,...,...
495,V0496,2025-01-31,C001,P004,7.0,120.0,0.15,Boleto
496,V0497,2025-12-26,C007,P007,7.0,150.0,0.00,Cartão
497,V0498,2025-06-08,C002,P005,2.0,18.0,0.15,Cartão
498,V0499,2025-06-17,C009,P003,7.0,890.0,0.15,Pix
499,V0500,2025-05-03,C007,P005,1.0,18.0,0.00,Pix

  cliente_id        cliente          cidade estado
0       C001      Ana Souza      São Carlos     SP
1       C002     Bruno Lima      Araraquara     SP
2       C003   Carla Mendes  Ribeirão Preto     SP
3       C004    Diego Alves        Campinas     SP
4       C005      Eva Costa           Bauru     SP
5       C006   Felipe Rocha       São Paulo     SP
6       C007    Gabi Santos             Jaú     SP
7       C008   Hugo Martins      Piracicaba     SP
8       C009  Iara Oliveira          Franca     SP
9       C010   João Pereira         Limeira     SP

  produto_id  produto    categoria  preco_unitario
0       P001  Cadeira       Móveis           180.0
1       P002     Mesa       Móveis           420.0
2       P003  Monitor  Eletrônicos           890.0
3       P004  Teclado  Eletrônicos           120.0
4       P005  Caderno    Papelaria            18.0
5       P006   Caneta    Papelaria             4.5
6       P007  Mochila   Acessórios           150.0
7       P008     Fone  Eletrônicos           210.0